// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmhxsceedfcsdlugkilo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtaHhzY2VlZGZjc2RsdWdraWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzI4OTcsImV4cCI6MjA2NDEwODg5N30.xtffD2ItfTtfxeyr2XH-jHcwgx3-lYksQV2PSPLWRd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);